config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#search'
  resources :unique_routes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 # root 'sessions#new'
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unique_route.rb
class UniqueRoute < ApplicationRecord
searchkick
def search_data
{
dep_city_code: dep_city_code,
arr_city_code: arr_city_code,
arr_city_name: arr_city_name,
dep_city_name: dep_city_name,
schedule_route_url: schedule_route_url
}
end

#UniqueRoute.reindex
end

app/models/user.rb
class User < ApplicationRecord
	 has_secure_password  
	 validates :email, presence: true, uniqueness: true
	 validates_length_of       :password, maximum: 72, minimum: 5, allow_nil: true, allow_blank: false
  	 validates_confirmation_of :password, allow_nil: true, allow_blank: false

  before_validation { 
    self.email = self.email.to_s.downcase 
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

helper_method :current_user  

 def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

   def not_found
    render json: { error: 'not_found' }
  end

  def authorize_request
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JsonWebToken.decode(header)
      @current_user = User.find(@decoded[:user_id])
    rescue ActiveRecord::RecordNotFound => e
      render json: { errors: e.message }, status: :unauthorized
    rescue JWT::DecodeError => e
      render json: { errors: e.message }, status: :unauthorized
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 	
  def index
  	if params[:q].nil?
      @unique_routes = []
    else
      @unique_routes = UniqueRoute.search params[:q]
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  

  def search
    if params[:q].nil?
      @unique_routes = []
    else
      @unique_routes = UniqueRoute.search params[:q]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  require "json_web_token"  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      token = JsonWebToken.encode(user_id: user.id)
      time = Time.now + 24.hours.to_i
      session[:user_id] = user.id
       redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

  
end

app/controllers/unique_routes_controller.rb
class UniqueRoutesController < ApplicationController
 	before_action :authenticate_user!


def index
	query = params[:q].presence || “*”
	@articles = UniqueRoute.search(query)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to login_path  
      else
        redirect_to signup_path
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/unique_routes_helper.rb
module UniqueRoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>  <%= link_to 'Log Out', logout_path %>
<h1>Unique routes Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<table>
  <thead>
    <tr>
      <th>Departure City Code</th>
      <th>Arrival City Code</th>
      <th>Weekly Flights Count</th>
      <th>Distance</th>
      <th>HOP</th>
      <th>Departure City Name</th>
      <th>Arrival City Name</th>
      <th>Schedule Route Url</th>
      <th>Departure City Name AR</th>
      <th>Arrival City Name AR</th>
    </tr>
  </thead>
 
  <tbody>

    <% @unique_routes.each do |book| %>
      <tr>
        <td><%= book.dep_city_code %></td>
        <td><%= book.arr_city_code %></td>
        <td><%= book.weekly_flights_count %></td>
        <td><%= book.distance %></td>
        <td><%= book.hop %></td>
        <td><%= book.dep_city_name %></td>
        <td><%= book.arr_city_name %></td>
        <td><%= book.schedule_route_url %></td>
        <td><%= book.dep_city_name_ar %></td>
        <td><%= book.arr_city_name_ar %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <%= link_to 'Sign Up', signup_path %> or 
  <%= link_to 'Log In', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElasticSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<h1>Unique routes Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<table>
  <thead>
    <tr>
      <th>Departure City Code</th>
      <th>Arrival City Code</th>
      <th>Weekly Flights Count</th>
      <th>Distance</th>
      <th>HOP</th>
      <th>Departure City Name</th>
      <th>Arrival City Name</th>
      <th>Schedule Route Url</th>
      <th>Departure City Name AR</th>
      <th>Arrival City Name AR</th>
    </tr>
  </thead>
 
  <tbody>

    <% @unique_routes.each do |book| %>
      <tr>
        <td><%= book.dep_city_code %></td>
        <td><%= book.arr_city_code %></td>
        <td><%= book.weekly_flights_count %></td>
        <td><%= book.distance %></td>
        <td><%= book.hop %></td>
        <td><%= book.dep_city_name %></td>
        <td><%= book.arr_city_name %></td>
        <td><%= book.schedule_route_url %></td>
        <td><%= book.dep_city_name_ar %></td>
        <td><%= book.arr_city_name_ar %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<script>
</script>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', login_path %>